export const passwordTypes = Object.freeze({
  CREATE_INFO: 'CREATE_INFO',
  UPDATE_INFO: 'UPDATE_INFO',
  DELETE_INFO: 'DELETE_INFO',
  FINISH_INFO: 'FINISH_INFO',
  FETCH_INFO: 'FETCH_INFO',
  SET_ERROR: 'SET_ERROR',
});
