export const tasksTypes = Object.freeze({
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  FINISH_TASK: 'FINISH_TASK',
  FETCH_TASKS: 'FETCH_TASKS',
  SET_TASKS_ERROR: 'SET_TASKS_ERROR',
});
